language: csharp
mono: none
dotnet: 2.1
addons:
  sonarcloud:
    organization: 'donkeykongjr-github'

before_install:
  - bash ./tools/travis-install-dependencies.sh

script:
  - bash ./tools/travis-build.sh
